[features]
seeds = false
skip-lint = false
[programs.localnet]
packs_program = "ASqbFGxqkxMJWcG25pguvvS5p2JAQToR3HLMVV8T3WNL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/aioz-quang-le/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
